# -*- coding: utf-8 -*-
"""Streamlit_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125pxBRJGuzb-Yu0tw3mSc35oaL9mcTbX
"""

import streamlit as st
import pickle
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

# Load trained model
with open("mnist_model.pkl", "rb") as f:
    model = pickle.load(f)

# Load digits dataset
digits = load_digits()
X = digits.images.reshape((1797, 64)) / 16.0  # normalized
y = digits.target

# App Title
st.title("🔢 Digit Classifier (0–9)")
st.write("This app uses a machine learning model to recognize handwritten digits.")

# Choose image index
index = st.slider("Choose an image index:", 0, len(X)-1, 0)

# Show the image
st.image(digits.images[index], width=150, caption=f"Actual Digit: {y[index]}", clamp=True)

# Predict the digit
prediction = model.predict([X[index]])[0]
st.subheader(f"📌 Model Prediction: {prediction}")

# Compare
if prediction == y[index]:
    st.success("✅ Correct Prediction")
else:
    st.error("❌ Wrong Prediction")